spring.application.name=coursera
logging.level.org.springframwork =trace

##trace, debug, info, warning, error and off

currency-service.url=https://api.dev.com/currency
currency-service.username=devname
currency-service.key=devkey