spring.application.name=coursera
logging.level.org.springframwork =debug

spring.profiles.active=dev
currency-service.url=https://api.example.com/currency
currency-service.username=changeme
currency-service.key=changeme



management.endpoints.web.exposure.include=*

server.port = 8080